<?php

/**
 * @file
 * Contains uw_auth.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uw_auth_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the uw_auth module.
    case 'help.page.uw_auth':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('UW Auth via weblogin') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function uw_auth_theme() {
  return array('uw_auth' => 
    array(
      'variables' => array(
        'shibauth' => null,
        'base_url' => null,
        'uid' => null,
        'uname' => null,
        'isannon' => null,
      ),
      'template' => 'uw_auth',
    )
  );
}}